version: '3.8'

services:
  # --- ğŸ˜ PostgreSQL (Database à¸«à¸¥à¸±à¸) ---
  postgres:
    image: postgres:14-alpine
    container_name: nest_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: address_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- ğŸ”´ Redis (à¸„à¸§à¸²à¸¡à¸ˆà¸³à¸Šà¸±à¹ˆà¸§à¸„à¸£à¸²à¸§à¸ªà¸³à¸«à¸£à¸±à¸šà¸šà¸­à¸—) ---
  redis:
    image: redis:alpine
    container_name: nest_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
